name: Push/PR

on: [push, pull_request]

jobs:
  test:
    name: Test Packages With Changed Files
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Checkout
      run: |
        git fetch --no-tags --prune --depth=1 origin +refs/heads/*:refs/remotes/origin/*
    - name: Set up Node (10)
      uses: actions/setup-node@v1
      with:
        node-version: 10.x
    - name: install Chrome stable
      run: |
        sudo apt-get update
        sudo apt-get install google-chrome-stable
    - name: Test setup and yarn install
      run: |
        cp config/ci.config.json config/project.json
        yarn
    - name: yarn build
      run: yarn build
    - name: Run tests on changed packages
      run: xvfb-run yarn test:changed

  health-metrics-test:
    name: Health Metrics Test
    runs-on: ubuntu-latest
    env:
      METRICS_SERVICE_URL: ${{ secrets.METRICS_SERVICE_URL }}
      GITHUB_PULL_REQUEST_NUMBER: ${{ github.event.pull_request.number }}
      GITHUB_PULL_REQUEST_BASE_SHA: ${{ github.event.pull_request.base.sha }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 10.x
      - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          service_account_key: ${{ secrets.GCP_SA_KEY }}
      - run: cp config/ci.config.json config/project.json
      - run: yarn install
      - run: yarn build

      - name: Run health-metrics/binary-size test
        run: yarn size-report

      # TODO(yifany): Enable startup times testing on CI.
